print("Enter two numbers to be added!")
number1 = input ("First Number: ")
number2 = input ("Second Number: ")
answer = int(number1) + int(number2)
print(str(number1) + " + " + str(number2) + " = " + str(answer))